import java.util.Locale
import java.util.Properties

plugins {
    id("com.android.application")
}

val verCode = 11
val verName = "v1.1"
val pkgName = "top.yukonga.linkToWindows"
val moduleId = "LinkToWindows"
val androidBuildToolsVer = "37.0.0"

val androidSdkDir = run {
    val localProps = rootProject.file("local.properties")
    val fromProps = if (localProps.exists()) {
        Properties()
            .apply { localProps.reader().use { r -> load(r) } }
            .getProperty("sdk.dir")
    } else null
    val resolved = fromProps
        ?: System.getenv("ANDROID_HOME")
        ?: System.getenv("ANDROID_SDK_ROOT")
        ?: error("Android SDK not found; set sdk.dir in local.properties or ANDROID_HOME")
    file(resolved)
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

android {
    buildToolsVersion = androidBuildToolsVer
    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }
    compileSdk {
        version = release(37) {
            minorApiLevel = 0
        }
    }
    defaultConfig {
        applicationId = pkgName
        minSdk = 34
        targetSdk = 37
        versionCode = verCode
        versionName = verName
        ndk {
            abiFilters.add("arm64-v8a")
        }
    }
    enableKotlin = false
    externalNativeBuild {
        ndkBuild {
            path = file("jni/Android.mk")
        }
    }
    namespace = pkgName
    ndkVersion = "29.0.14206865"
}

// ---------------------------------------------------------------------------
// Embedded helper dex for runtime CROSS_DEVICE_SERVICE fetcher injection.
// Pipeline: compile helper/ -> d8 to classes.dex -> emit a C header that
// the JNI build #includes, so the dex bytes ride inside the .so.
// ---------------------------------------------------------------------------

val helperSrcDir = layout.projectDirectory.dir("helper")
val helperClassesDir = layout.buildDirectory.dir("helper/classes")
val helperDexDir = layout.buildDirectory.dir("helper/dex")
val helperHeaderFile = layout.buildDirectory.file("generated/jni/fetcher_dex.h")

val compileFetcherHelper = tasks.register<JavaCompile>("compileFetcherHelper") {
    source = fileTree(helperSrcDir) { include("**/*.java") }
    classpath = files()
    destinationDirectory.set(helperClassesDir)
    sourceCompatibility = JavaVersion.VERSION_1_8.toString()
    targetCompatibility = JavaVersion.VERSION_1_8.toString()
    options.compilerArgs.addAll(listOf("-implicit:none"))
}

val dexFetcherHelper = tasks.register<JavaExec>("dexFetcherHelper") {
    dependsOn(compileFetcherHelper)
    val d8Jar = file("$androidSdkDir/build-tools/$androidBuildToolsVer/lib/d8.jar")
    inputs.dir(helperClassesDir)
    inputs.file(d8Jar)
    outputs.dir(helperDexDir)
    classpath = files(d8Jar)
    mainClass.set("com.android.tools.r8.D8")
    doFirst {
        helperDexDir.get().asFile.deleteRecursively()
        helperDexDir.get().asFile.mkdirs()
    }
    argumentProviders.add(CommandLineArgumentProvider {
        buildList {
            add("--output")
            add(helperDexDir.get().asFile.absolutePath)
            add("--min-api")
            add("26")
            helperClassesDir.get().asFileTree
                .matching { include("**/*.class") }
                .files
                .sortedBy { it.path }
                .forEach { add(it.absolutePath) }
        }
    })
}

val generateFetcherHeader = tasks.register("generateFetcherHeader") {
    dependsOn(dexFetcherHelper)
    val dexFile = helperDexDir.map { it.file("classes.dex") }
    inputs.file(dexFile)
    outputs.file(helperHeaderFile)
    doLast {
        val bytes = dexFile.get().asFile.readBytes()
        val out = helperHeaderFile.get().asFile
        out.parentFile.mkdirs()
        out.writer().use { w ->
            w.write("// Auto-generated by :module:generateFetcherHeader. Do not edit.\n")
            w.write("#pragma once\n")
            w.write("#include <cstddef>\n")
            w.write("#include <cstdint>\n\n")
            w.write("inline constexpr uint8_t kFetcherDex[] = {\n")
            bytes.forEachIndexed { i, b ->
                if (i % 16 == 0) w.write("    ")
                w.write(String.format(Locale.ROOT, "0x%02x,", b.toInt() and 0xff))
                w.write(if (i % 16 == 15 || i == bytes.lastIndex) "\n" else " ")
            }
            w.write("};\n")
            w.write("inline constexpr size_t kFetcherDexLen = sizeof(kFetcherDex);\n")
        }
    }
}

afterEvaluate {
    tasks.matching { it.name.startsWith("externalNativeBuild") }
        .configureEach { dependsOn(generateFetcherHeader) }
}

tasks.register<Zip>("assembleModule") {
    group = "module"

    val apkFile = layout.buildDirectory.file("outputs/apk/release/module-release-unsigned.apk")
    val apkTree = zipTree(apkFile.get().asFile)

    from(apkTree) {
        include("lib/**", "assets/**")
        exclude("assets/module.prop")
        eachFile {
            path = when {
                path.startsWith("lib/") -> buildString {
                    val startIndex = path.indexOf('/') + 1
                    val endIndex = path.indexOf('/', startIndex)
                    append("zygisk/")
                    append(path.substring(startIndex, endIndex))
                    append(".so")
                }

                path.startsWith("assets/") -> path.removePrefix("assets/")

                else -> path
            }
        }
    }

    from(file("src/main/assets/module.prop")) {
        filter { line ->
            line.replace("%%VERSION%%", verName)
                .replace("%%VERSIONCODE%%", verCode.toString())
        }
    }

    destinationDirectory.set(layout.buildDirectory.dir("outputs/module"))
    archiveFileName.set("${moduleId}_${verName}.zip")
}

afterEvaluate {
    tasks["assembleModule"].dependsOn(tasks["assembleRelease"])
}
